### ISSUE TITLE
Seems to crash without the Twigs mod

### ISSUE THREAD

**Issue by ThePegNok** [KekeCreations/Arts-and-Crafts-Compatibility#1]
Upon world creation the mod seems to crash without the mod Twigs as it misses silt

Logs related:

[latest.log](https://github.com/user-attachments/files/15801000/latest.log)

**Comment by KekeCreations** [comment]
Mhmm never had this issue, do you continue to have this issue with just Arts & Crafts, Arts & Crafts Compat and Twigs installed?

**Comment by ThePegNok** [comment]
Yup, same behavior. 
[crash-2024-06-12_14.09.16-client.txt](https://github.com/user-attachments/files/15808556/crash-2024-06-12_14.09.16-client.txt)
[latest.log](https://github.com/user-attachments/files/15808560/latest.log)

**Comment by KekeCreations** [comment]
Fixed in V1.0.4
