### ISSUE TITLE
Cork variant blocks are disabled when they shouldn't be

### ISSUE THREAD

**Issue by emihead** [KekeCreations/Arts-and-Crafts-Compatibility#10]
Hi! I noticed that the Cork variant blocks are disabled for whatever reason. I'm not sure what mod they were added as compatibility for, but I have Woodworks and Building But Better installed, which each add some of those variants themselves (Woodworks adds all of them minus the crafting table, BBB only adds ladders). It would be great if they could also function as compat with those mods, or if there could just be configs for manually enabling or disabling certain things.

**Comment by emihead** [comment]
I just checked what all is disabled that's filled in by other mods, here's a list:
Bookshelf (Woodworks)
Decorative Bookshelf (Also Woodworks, they're called Chiseled Bookshelves in that mod and crafted with slabs instead of books)
Ladder (BBB and Woodworks, although BBB's ladders are implemented differently and have variants you can cycle through, so it might just work better as Woodworks compat)

**Comment by KekeCreations** [comment]
These cork blocks were added as compat for Excessive Building and Yirmiri won't allow me to use the textures they made for compat for other mods.

**Comment by KekeCreations** [comment]
I'm sorry seems I don't have permission to use these textures outside of Excessive Building there isn't much I can do!
