### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by SaltSouls** [KekeCreations/Arts-and-Crafts-Compatibility#11]
Right now the mod spams the console when trying to load recipes from mods that aren't installed. I would recommend you look at conditional recipes to make it so they only load when the mod is actually present. This will remove a ton of spam player get in their log files and will make it easier for them to find actual problems with this/other mods.

**Comment by emihead** [comment]
Yeah I'm noticing this too. Really annoying. It's excessive building items in loot tables for me

**Comment by KekeCreations** [comment]
Hi, I tackled some of the log spam in V1.3.0, I will get rid of what I can, when I can, seems it doesn't break the mod, it isn't a high priority compared to other bugs!

**Comment by KekeCreations** [comment]
I fixed all log spam in V1.3.1, thank you for reporting bugs!
