### ISSUE TITLE
v1.2.0+ crashes when installed alongside Decorative Blocks

### ISSUE THREAD

**Issue by unilock** [KekeCreations/Arts-and-Crafts-Compatibility#12]
When Arts & Crafts Compatibility version 1.2.0 or higher is installed alongside [Decorative Blocks](https://modrinth.com/mod/decorative-blocks), the game crashes during startup.

Crash log: https://gist.github.com/unilock/28032d33c0944ae691b417eaf491e65b

I believe this is because one of this mod's mixins disables remapping on a vanilla method, so the mod will work in a dev environment (where everything is remapped to named), but not in a production environment (where intermediary mappings are used).

https://github.com/KekeCreations/Arts-and-Crafts-Compatibility/blob/8e36a91ac5776fd5ea2ad1fdee99f856fbda14a2/common/src/main/java/com/kekecreations/arts_and_crafts_compatibility/core/mixin/PalisadeBlockMixin.java#L16

Removing `remap = false` should resolve the issue.

**Comment by KekeCreations** [comment]
Thank you for reporting bugs! This issue was fixed in V1.2.2.

You were right that was the problem, turns out this crash didn't exist on Forge though! (Just fabric and Quilt)
The update just dropped on Curseforge & Modrinth!
