### ISSUE TITLE
V.1.0.3 for Forge Makes Pickaxes Unable to Break Blocks

### ISSUE THREAD

**Issue by RegalRuffRaff** [KekeCreations/Arts-and-Crafts-Compatibility#2]
The compatibility mod makes it so that pickaxes can no longer break blocks (tested with wood and stone on Vanilla and modded blocks). Version 1.0.3 for Forge, tested without the compatibility mod, the standalone Arts & Crafts works fine.

Forge 47.2.4
Arts & Crafts 1.0.3
Arts & Crafts Compatibility 1.0.3

Sorry if the modlist is a mess, I wasn't sure how to compress it better for a spoiler.

<!DOCTYPE html> 
<head> 
<head> 
	
</head> 
<body> 
	<details> 
		<summary>[My Mods List (Arts and Crafts Compatibility not included)]</summary> 
		2.0.0-BFT_mod-1.19-1.20.4.jar 
3dskinlayers-forge-1.5.4-mc1.20.1.jar 
AdditionalBanners-Forge-1.20.1-14.0.4.jar AdvancementPlaques-1.20.1-forge-1.5.1.jar adv_nuker-1.20-1.3.jar alexscaves-1.1.4.jar alexscavestrimmed-1.0.2.jar alexsdelight-1.5.jar
alexsmobs-1.22.8.jar
all_bark_all_bite-1.20.1-1.0.2.jar
amendments-1.20-1.1.27.jar
another_furniture-forge-1.20.1-3.0.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
ArchaeologyBanners-Forge-1.20.1-5.1.5.jar
Architects-Palette-1.20.1-1.3.6.1.jar
architectury-9.2.14-forge.jar
artifacts-forge-9.5.7.jar
arts_and_crafts-forge-1.20.1-1.0.3.jar
ash_api-forge-3.0.2+1.20.1.jar
astikorcarts-1.20.x-1.1.6.jar
auto_third_person-forge-1.20.1-2.1.jar
a_good_place-1.20-1.2.3.jar
BadMobs-1.20.1-19.0.4.jar
balm-forge-1.20.1-7.1.4.jar
basicweapons-forge-mc1.20.1+1.2.0.jar
bbb-1.20.1-forge-1.0.1.jar
beautify-2.0.2.jar
BedBenefits-Forge-1.20.1-13.0.3.jar
BetterAdvancements-1.20.1-0.3.2.161.jar
betterarcheology-1.1.9-1.20.1.jar
BetterClouds-1.0.jar
bettercombat-forge-1.7.3+1.20.1.jar
betterfpsdist-1.20.1-4.4.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
BetterTridents-v8.0.1-1.20.1-Forge.jar
bigbrain-1.20-1.7.3.jar
bigfish-1.20.1-1.1.1.jar
BiomeParticleWeather-v4.1.0-1.20.1-Forge.jar
blossom-forge-1.20.1-1.0.7.jar
blueprint-1.20.1-7.1.0.jar
Bookshelf-Forge-1.20.1-20.1.9.jar
bountiful_critters-1.2.2.jar
bwncr-forge-1.20.1-3.17.0.jar
caelus-forge-3.1.0+1.20.jar
campchair.forge.1.20-1.0.3.jar
canary-mc1.20.1-0.3.3.jar
cardboardboxes-1.20-0.1.0.jar
carryon-forge-1.20.1-2.1.2.7.jar
catalogue-forge-1.20.1-1.8.0.jar
caveoverhaul-forge-1.20.1-1.2.2-fixed.jar
chainmailed-1.3.jar
chalk-1.20.1-1.6.4.jar
Chalked_1.2-1.20.1-Forge.jar
charmofundying-forge-6.4.2+1.20.1.jar
Chimes-v2.0.1-1.20.1.jar
citadel-2.5.4-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-7.3.jar
collectorsreap-1.20.1-1.3.jar
comforts-forge-6.3.3+1.20.1.jar
CorgiLib-forge-1.20.1-4.0.0.4.jar
corn_delight-1.0.4-1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CosmeticArmours - 1.3.7.1 - 1.20.1 - Forge.jar
CrabbersDelight-1.20.1-1.1.4.jar
cratedelight-2024.05.05-1.20.1-forge.jar
cupboard-1.20.1-2.0.jar
curios-forge-5.9.1+1.20.1.jar
DeathKnell-Forge-1.20.1-10.0.4.jar
Delightful-1.20.1-3.5.5.jar
delightfulburgers-1.20.1.jar
delightfulsandwich-1.20.1.jar
domesticationinnovation-1.7.0-1.20.jar
doubledoors-1.20.1-5.0.jar
Dungeon Now Loading-forge-1.20.1-1.5.jar
dungeons_plus-1.20.1-1.5.0.jar
EasyAnvils-v8.0.1-1.20.1-Forge.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
ecologics-forge-1.20.1-2.2.0.jar
EffectDescriptions-v8.0.2-1.20.1-Forge.jar
elytraslot-forge-6.3.0+1.20.1.jar
elytratrims-forge-2.1.2+1.20.1.jar
embeddium-0.3.20+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.12.jar
EnchantingInfuser-v8.0.2-1.20.1-Forge.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.13.jar
enchantmenttransfer-0.0.6-1.20.1.jar
EndlessBiomes 1.5.1 - 1.20.1.jar
endportalparallax-2.1.1-mc1.20.1-forge.jar
endrem_forge-5.2.3-R-1.20.X.jar
ends_delight-1.20.1-1.0.1.jar
enhanced_mushrooms-5.0.0.jar
entityculling-forge-1.6.5-mc1.20.1.jar
entity_model_features_forge_1.20.1-2.0.2.jar
entity_texture_features_forge_1.20.1-6.0.1.jar
Etcetera-1.20.1-1.1.3-Forge.jar
everycomp-1.20-2.6.58.jar
extendedbonemeal-1.20.1-3.0.jar
extra_compat-1.4.13.jar
FarmersDelight-1.20.1-1.2.4.jar
farsight-1.20.1-3.6.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
fastpaintings-1.20-1.2.0.jar
FastSuite-1.20.1-5.0.1.jar
ferritecore-6.0.1-forge.jar
fishermens_trap-2.1.2.jar
fishnostuck-mc1.20.1-v1.0.3-forge.jar
fixedanvilrepaircost-1.20.1-3.1.jar
flatbedrock-forge-3.0.1-build.18+mc1.20.1.jar
flourish-forge-3.0.0+1.20.1.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
forgivingvoid-forge-1.20-10.0.0.jar
FpsReducer2-forge-1.20-2.5.jar
framework-forge-1.20.1-0.6.26.jar
FriendlyFire-Forge-1.20.1-18.0.5.jar
friendsandfoes-forge-mc1.20.1-2.0.10.jar
geckolib-forge-1.20.1-4.4.4.jar
geophilic-v2.2.0-mc1.20u1.20.2.jar
getittogetherdrops-forge-1.20-1.3.jar
GildedSherds-Forge-1.20.1-1.0.2.jar
goated-1.20-1.3.4.jar
golemsarefriends-1.20.0-1.0.1.jar
gravestone-forge-1.20.1-1.0.14.jar
habitat-1.3.1.jar
hauntedharvest-1.20-3.1.20.jar
hearth_and_home-forge-1.20.1-2.0.3.jar
Highlighter-1.20.1-forge-1.1.9.jar
hourglass-1.20-1.2.1.1.jar
huskspawn-1.20.1-3.3.jar
Iceberg-1.20.1-forge-1.1.21.jar
ImmediatelyFast-1.2.7+1.20.2.jar
immersive_weathering-1.20.1-2.0.0-forge.jar
inkandquill-0.1.0-1.20.1.jar
ItemBorders-1.20.1-forge-1.2.1.jar
ItemsDisplayedForge+-+v1.2.1-1.20.1.jar
jei-1.20.1-forge-15.2.0.27.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
KryptonReforged-0.2.3.jar
labels-1.20-1.16.jar
lapidary-3.1-1.20.1.jar
leatheroverhaul-forge-1.20.1-1.1.3.jar
LeavesBeGone-v8.0.0-1.20.1-Forge.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
letfishlove-2.0.4.jar
lootbeams-1.20.1-1.2.5.jar
lootr-1.20-0.7.31.78.jar
majrusz-library-forge-1.20.1-7.0.5.jar
majruszs-accessories-forge-1.20.1-1.5.1.jar
majruszs-enchantments-forge-1.20.1-1.10.7.jar
map_atlases-1.20-6.0.6.jar
marigoldrings-1.0.0-1.20.1.jar
marigolds-1.0.4-1.20.1.jar
memoryleakfix-forge-1.17+-1.1.2.jar
MerchantMarkers-1.20.1-forge-1.3.3.jar
midnightlib-forge-1.4.2.jar
miners_delight-1.20.1-1.2.3.jar
modernfix-forge-5.18.1+mc1.20.1.jar
mods.txt
moonlight-1.20-2.11.13-forge.jar
moredelight-1.1.2-1.20.1-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
mowziesmobs-1.6.4.jar
moyai-1.20-2.0.2.jar
musicmanager-1.20.1-1.3.15.jar
MyNethersDelight-1.20.1-1.6.2.jar
mysterious_mountain_lib-1.4.5-1.20.1.jar
namepain-1.5.1+forge-1.20.x.jar
naturallychargedcreepers-1.20.1-3.2.jar
Neat-1.20-35-FORGE.jar
nerb-1.20.1-0.3-FORGE.jar
netherdepthsupgrade-3.1.5-1.20.jar
nethers_exorcism-0.3.1D.jar
New+Death+Messages+Mod.jar
nocube's_villagers_sell_animals_1.2.1_forge_1.20.1.jar
nohostilesaroundcampfire-1.20.1-5.7.jar
notenoughanimations-forge-1.7.3-mc1.20.1.jar
notenoughcrashes-4.4.6+1.20.1-forge.jar
nyfsspiders-forge-1.20.1-2.1.1.jar
ObsidianUI-forge-0.2.1+mc1.20.1.jar
oculus-mc1.20.1-1.6.15a.jar
OhMySherd-Forge-1.20.1-1.0.3.jar
OverflowingBars-v8.0.0-1.20.1-Forge.jar
overweightfarming-1.20.1-2.1.0-forge.jar
packedup-0.1.1-beta.jar
panorama_screens-1.0+forge+mc1.20.jar
paperdoll-forge-1.1.1-mc1.20.jar
ParCool-1.20.1-3.1.0.5-R.jar
passiveshield-1.20.1-3.2.jar
Patchouli-1.20.1-81-FORGE.jar
phantasm-forge-0.2.jar
Philips-Biome-Features1.20x-1.2.jar
Philips-Ruins1.20.1-3.9.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
piglinproliferation-1.20.1-1.2.1.jar
Placebo-1.20.1-8.3.7.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.5+1.20.1.jar
Prism-1.20.1-forge-1.0.5.jar
puzzledungeon-forge-1.20.1-1.2.0.jar
PuzzlesLib-v8.1.19-1.20.1-Forge.jar
qualitysounds-forge-1.5.0-1.20.1.jar
radiantgear-forge-2.1.5+1.20.1.jar
Random Crits 1.3.2 - 1.20.1.jar
replantingcrops-1.20.1-5.1.jar
repurposed_structures-7.1.15+1.20.1-forge.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
resourcefullib-forge-1.20.1-2.1.16.jar
responsiveshields-2.2.jar
right-click-harvest-3.2.3+1.20.1-forge.jar
riverredux-0.3.1.jar
RyoamicLights-forge-0.2.0+mc1.20.1.jar
salt-1.20.1-1.2.4.jar
saturn-mc1.20.1-0.1.1.jar
sawmill-1.20-1.3.11.jar
scuba_gear-1.20.1-1.0.6.jar
seasonhud-forge-1.20.1-1.5.9.jar
sereneseasonfix-1.20.1-1.0.8.jar
SereneSeasons-1.20.1-9.0.0.46.jar
SewingKit-1.20.1-1.8.1.jar
Shield_Overhaul-FORGE-MC1.20.1-1.0.3.jar
Simple Enchantments 1.3.3 - 1.20.1.jar
smarterfarmers-1.20-1.8.3.jar
Sniffer+-forge-1.20.1-0.3.0.jar
snifferent-1.0.3-1.20.1.jar
snowyspirit-1.20-3.0.6.jar
solapplepie-1.20.1-2.3.0.jar
sootychimneys-1.20.1-1.1.1.jar
sound-physics-remastered-forge-1.20.1-1.3.1.jar
spelunkery-1.20.1-0.3.5-forge.jar
spidersproducewebs-1.20.1-3.1.jar
spyglass_improvements-1.5+mc1.20+forge.jar
squidnoglitch-mc1.19.4-1.20.x-v1.0.1-forge.jar
stackrefill-1.20.1-4.0.jar
starlight-1.1.2+forge.1cda73c.jar
StonyCliffs-v1.0.0.jar
storagedelight-1.1.0-1.20.1-forge.jar
strayspawn-1.20.1-3.3.jar
structure_gel-1.20.1-2.16.0.jar
StylishEffects-v8.0.2-1.20.1-Forge.jar
supplementaries-1.20-2.8.10.jar
suppsquared-1.20-1.1.14.jar
tact-1.1.5+1.20.1.jar
temporalapi-1.5.0.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
the-conjurer-1.20.1-1.1.6.jar
thigh_highs_etc-forge-1.0.4.jar
TinySkeletons-v8.0.1-1.20.1-Forge.jar
Tips-Forge-1.20.1-12.0.3.jar
tlc_forge-1.0.3-R-1.20.X.jar
ToolBelt-1.20.1-1.20.01.jar
TravelersTitles-1.20-Forge-4.0.2.jar
treeharvester-1.20.1-8.2.jar
twigs-1.20.1-3.1.0-forge.jar
u_team_core-forge-1.20.1-5.1.4.269.jar
vegandelight-1.2.jar
veinmining-forge-1.4.1+1.20.1.jar
venturer-1.0.3-1.20.1.jar
verdantvibes-1.0.3-1.20.1.jar
villagernames-1.20.1-6.2.jar
visuality-forge-2.0.2.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
wardrobe-1.0.3.1-forge-1.20.1.jar
waystones-forge-1.20-14.0.2.jar
weakerspiderwebs-1.20.1-3.2.jar
Wealthy And Growth-1.20.1-4.0.0.jar
wildberries-1.3.0[forge-1.20.1].jar
woodenshears-1.20-1.4.0.1.jar
wooltweaks-1.20.1-3.1.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
[1.20.1] Simply Light Sources v1.0.0 (Forge).jar

		 
</body> 
</html>

**Comment by KekeCreations** [comment]
you uploaded this at the perfect time, I'm rewriting it right now!

**Comment by KekeCreations** [comment]
Fixed with V1.0.4
