### ISSUE TITLE
New version breaks all #minecraft:mineable/ tags

### ISSUE THREAD

**Issue by Ellishaa** [KekeCreations/Arts-and-Crafts-Compatibility#9]
When you first load the world, all `#minecraft:mineable/` tags are disabled. If you disable the mod datapack it works. It seems to have trouble loading blocks that don't exist.

Note : If you disable then reeanble the mod datapack, tags work again, but not for blocks added by arts & crafts compat, but I think this is due to datapack ordering.

**Comment by KekeCreations** [comment]
Thank you for reporting this, I'll look into it rn!

**Comment by KekeCreations** [comment]
Fixed in V1.2.1, I'm sorry that this bug ever existed, V1.2.0 shouldn't of released in this state!
